
#ifdef SPEW3D_IMPLEMENTATION

#define STB_VORBIS_NO_STDIO
#define STB_VORBIS_HEADER_ONLY
#ifndef __STRICT_ANSI__
#define UNDEF_STRICT_ANSI_LATER
#define __STRICT_ANSI__
#endif
#define DR_FLAC_IMPLEMENTATION
#define DR_MP3_IMPLEMENTATION
#define DR_WAV_IMPLEMENTATION

